// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhXjX4Ko-68ZQmzAU09t7FiavHAduYDQE',
    appId: '1:108208997647:android:75efe1f1672ca185116a7a',
    messagingSenderId: '108208997647',
    projectId: 'syi-app',
    storageBucket: 'syi-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASZz0XB2U-EGq7rXNSUWzJf3sFU0b1ijc',
    appId: '1:108208997647:ios:40bb76ee3f046aa9116a7a',
    messagingSenderId: '108208997647',
    projectId: 'syi-app',
    storageBucket: 'syi-app.appspot.com',
    androidClientId: '108208997647-ndk4rpb80fhi6m0s6nq523e2la26kcv8.apps.googleusercontent.com',
    iosClientId: '108208997647-1imccplave3qboa0cdqsms542epg0c1g.apps.googleusercontent.com',
    iosBundleId: 'com.encro.syi.syi',
  );
}
